Module2 task1
htmlacademy-adaptive/2087061-mishka-26 pull request #3
Opened 2022-08-03 08:27 UTC by pppushinw

2022-08-03 18:00 UTC, blckwltz requested changes

2022-08-03 18:00 UTC, blckwltz commented on source/index.html
> +              <h1 class="visually-hidden">Логотип компании</h1>
@pppushinw "Логотип компании" не очень подходит на роль главного заголовка страницы, хорошо бы что-то более содержательное придумать 🙂

2022-08-03 18:00 UTC, blckwltz commented on source/index.html
> +                          </svg>
@pppushinw на мой взгляд излишне добавлять эти изображения в разметку, у них при взаимодействии меняется только прозрачность, можно сделать псевдоэлементами

2022-08-03 18:00 UTC, blckwltz commented on source/index.html
> +                  </ul>
@pppushinw это скорее таблица, а не список

2022-08-03 18:00 UTC, blckwltz commented on source/index.html
> +                      <img src="img/index/icon-1.svg" alt="">
@pppushinw это изображения скорее декоративные, без них смысл текста не потеряется. Можно сделать фоном/псевдоэлементом

2022-08-03 18:00 UTC, blckwltz commented on source/index.html
> +                  <button>Написать</button>
@pppushinw по [ТЗ](https://up.htmlacademy.ru/adaptive/26/project/mishka#mishka-4-5) это должна быть ссылка

2022-08-03 18:00 UTC, blckwltz commented on source/index.html
> +                  </div>
@pppushinw тут лучше использовать кнопки, подразумевается, что они будут пролистывать отзывы

2022-08-03 18:00 UTC, blckwltz commented on source/index.html
> +              <ul class="social__list">
@pppushinw тут получается элемент блока `social`, но самого блока нет

2022-08-03 18:00 UTC, blckwltz commented on source/catalog.html
> +                            <h4>Зайчик-попрыгайчик</h4>
@pppushinw 
- по [ТЗ](https://up.htmlacademy.ru/adaptive/26/project/mishka#mishka-6-1) изображение и название должны быть ссылками
- пропущен один уровень заголовков, после `h2` сразу идет `h4`

2022-08-03 18:00 UTC, blckwltz commented on source/catalog.html
> +                    <h4>Процесс производства</h4>
@pppushinw тут тоже нужно сделать заголовок на один уровень выше

2022-08-03 18:00 UTC, blckwltz commented on source/form.html
> +            <form action="https://echo.htmlacademy.ru/" class="product__form" method="post">
@pppushinw здесь и дальше есть элементы блока `product`, но самого блока нет

2022-08-03 18:00 UTC, blckwltz commented on source/form.html
> +                    <label class="catalog">тип</label>
@pppushinw кажется, что этот и аналогичные лэйбле лишние, дальше ведь `legend` с таким же текстом

2022-08-03 18:00 UTC, blckwltz commented on source/form.html
> +                        </ul>
@pppushinw здесь и дальше в аналогичных местах:
- список является элементом блока `catalog`, но при этом самого блока нет (вернее есть, но это тот самый лишний лэйбл и список в любом случае в него не вложен)
- на мой взгляд список тут в принципе лишний, `fieldset` самого по себе достаточно для группировки полей формы

2022-08-04 10:06 UTC, blckwltz approved these changes

2022-08-04 10:06 UTC, blckwltz commented on source/catalog.html
> +                <span class="visually-hidden">Логотип компании</span>
@pppushinw теперь на странице вообще нет заголовка первого уровня. Нужно либо тут поменять текст, либо сделать заголовком первого тот, который идет первым в `main`. Проверь на всех страницах

2022-08-04 10:06 UTC, merged

2022-08-04 10:42 UTC, pppushinw commented on source/catalog.html
> +                <span class="visually-hidden">Логотип компании</span>
исправил